version: "3.3"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html

    mysql:
        image: mysql:8.0.27
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_DATABASE: olimpic_school
            MYSQL_USER: olimpic_school
            MYSQL_PASSWORD: qwerty
        ports:
            - "3307:3306"
        volumes:
            - ./database/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3307
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8085:80
